version: "3.8"
services:
    django:
        build:
            context: ./django
        ports:
            - "8000:8000"

    nest.js:
        build:
            context: ./nest.js
        ports:
            - "3000:3000"
            
    nginx:
        restart: always
        build:
            context: ./nginx
        depends_on:
            - django
            - nest.js
        ports:
            - "80:80"