apiVersion: v1
kind: Service
metadata:
  name: python-django-svc
  labels:
    name: python-django-svc
    app: python-django-app
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30004
  selector:
    app: python-django-app