version: "3.8"
services:
    nodeserver:
        build:
            context: ./node
        ports:
            - "3000:3000"
            
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "443:443"
