---

- name: Install App Ubuntu servers
  hosts: all
  become: true
  become_user: root
  gather_facts: false

  tasks:
    - name: Update apt cache and make sure Curl, nginx  are installed
      apt:
        name: "{{ item }}"
        state: latest 
        update_cache: yes
      loop:
        - curl
        - nginx

    - name: Install apache httpd  
      apt:
        name: httpd
        state: latest

    - name: Install http
      apt: 
        name: http
        state: latest